### PR TITLE
Event-driven game with GUI, using Tkinter

### PR DESCRIPTION
**Pull request by kaprice**
GUI version of game.py, "gfx.py" can be used instead of game.py, if user wants to play the game with a graphical interface. All the key commands work, there is a status message bar. Game state is in a tile-based map

### CODE REVIEW

**Comment by alexkarpandrus** [comment]
I'm stunned, so great, huge work you did! Seems like you have an experience in programming :)
Did you start writing it without knowledges about how to use Tkinter? 
As I undersand the only one image to use is an image of map (map.png) and others are letters ( "W" for wizard), right?

**Comment by alexkarpandrus** [comment]
PIL doesn't run on Windows x64.
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pil helped

**Comment by kaprice** [comment]
> I'm stunned, so great, huge work you did! Seems like you have an experience in programming :)

Thanks! I went to college for Computer Science, but dropped out. Been programming on my own since, though. I started to get into game dev in C++. Honestly, this is the first time I really tried to learn Python. It was a little confusing, but I realized that Python is really fun and powerful.

> Did you start writing it without knowledges about how to use Tkinter?

Yeah, first time using Tkinter.

> As I undersand the only one image to use is an image of map (map.png) and others are letters ( "W" for wizard), right?

Yeah, the original code used letters as symbols for the characters. I retained the original code, and kinda "mapped" each 16x16 tile in the map.png to a symbol (like 'W') in my code.

**Comment by kaprice** [comment]
> What is Canvas here?

Canvas is a Tkinter "widget", that allows image manipulation. See line 77? create_image() is a method that will place an image on an x, y position on the canvas.

> What is an event?

See lines 150 to 159. I use Tk to bind events to methods. When doing so, the event is passed as a parameter to the method. As far as I know, you need a param in these methods to capture these events, otherwise I get this error:

> TypeError: attack() takes no arguments (1 given)

The 1 argument given is the event.

**Comment by alexkarpandrus** [comment]
Thank you for explanation! Great job!

**Comment by gdimike** [comment]
Wow! Well done!

**Comment by pytonc** [comment]
Great job!
Merged in your own branch on main repo. When you do updates, please issue pull request to the branch 'kaprice'.

**Pull request closed without merging**
