### PR TITLE
Remark was taken into account.

### PR DESCRIPTION
**Pull request by alexkarpandrus**

### CODE REVIEW

**Comment by alexkarpandrus** [comment]
I'm sorry, it might be impolite, but why you didn't merge my code?

**Comment by pytonc** [comment]
I'm sorry, but this code does not work. It throws up an error when trying to run it. I thought it would be better if you fixed the error and added the fountain to map yourself, and made sure that the game runs before I merge it.
I can of course fix the bug myself, and add the fountain, but since this is student project, I think it is better if you have the chance to do it yourself. I am sorry if you feel offended, it was certainly not meant that way. I think your contributions are very cool! I just don't want to interfere too much.

On a side note - I will be merging the updates in separate branches for now, yours will be "magic", until the end of contest, because constant changes to the master branch made it hard for people who are making the graphical representations to work. And at the end of the week we shall put it all together, maybe even have several "levels" for the game, with the different monsters and facilities :-) (there is one student working on making that possible, via configuration file)

**Comment by alexkarpandrus** [comment]
Oh that's what! I thought you disliked my code. Now it is clear, I'll fix and fork again.

Frankly, I do not really understand that branch thing. Separate branches means that I'll not see other student's changes, I will make the game myself, but with your conrol, right?

**Comment by pytonc** [comment]
You will be able to see other code, you will just have to chose to use the branch explicitly, to try it out. It is like a different version - you have the default one "master", that one uses by default. But you can "checkout" some other branch, and then you will be using that version of the code and can see what it does. I will test some of the current implementations to see that they work, and merge them into some gui branches that other students can check out :-)

You can look at this page - http://git-scm.com/book/en/Git-Branching-What-a-Branch-Is which describes a bit how the the branching works for simple cases.

Right now the "master" branch is "frozen" to make it easier for students working on more complex things, so that they don't have to change their code every day, because somebody else changed something. At the end of the week we will merge what will be possible back together. For the upcoming weeks we will probably have a bit more specific tasks of what to do, so that it's easier to collaborate. This is an experiment fo us too :)

**Comment by alexkarpandrus** [comment]
Aaa, you've just opened my eyes :). Now students can change code, but it all will be murged (possibly) at the and of the week, right? So it would be currently in time to murge  other(https://github.com/udacians/udacity/pull/14) graphical representation. We will be able to add our code (for example add fountain) to the both versions.
Btw, and this experoment is awesome!

**Pull request closed without merging**
